# Generated by Django 3.1.2 on 2020-10-15 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=100, null=True)),
                ('street', models.CharField(default=None, max_length=100, null=True)),
                ('building_number', models.CharField(default=None, max_length=5, null=True)),
                ('flat_number', models.IntegerField(blank=True, default=None, null=True)),
                ('postal_code', models.CharField(default=None, max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
