# Generated by Django 3.1.2 on 2020-10-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20201013_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='creation_date',
            new_name='creation_year',
        ),
    ]
