# Generated by Django 3.1.2 on 2020-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_order_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
