# Generated by Django 3.1.2 on 2020-10-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20201015_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
