CATEGORIES = (
    ('Karma'),
    ('Przekąski'),
    ('Spacery'),
    ('Higienia i pielęgnacja'),
    ('Miejsca do spania'),
    ('Zabawki'),
    ('Miski i poidełka'),
)

BRANDS = (
    ('Select Gold', 2004),
    ('Carny', 2014),
    ('Premiere', 1973),
    ('AniOne', 2000),
    ('FIT+FUN', 1990),
    ('Multifit', 2012),
    ('Trixie', 1999),
)

SHIPMENTS = (
    ('InPost', 9.99),
    ('Kurier DHL', 12.99),
    ('Poczta Polska', 6.99),
    ('Pocztex 24H', 15.99),
    ('Kurier DPD', 8.99),
    ('Furgonetka.pl', 7.99),
)

PRODUCTS = (
    ('Sensitive Adult Maxi 4kg',
     'Karma sucha SELECT GOLD Sensitive to idealne rozwiązanie dla psów, które mają skłonność do nietolerancji pokarmowej lub wrażliwy układ trawienny.',
     900, 89.99, 'Karma', 'Select Gold'),
    ('Meati 6 x 800 g',
     '71% mięsa i składników pochodzenia zwierzęcego: Wysoka zawartość mięsa i soczyste, naturalne kawałki mięsa w karmie Premiere Meati sprawiają, że jest to wyjątkowy i smaczny produkt.',
     920, 65.94, 'Karma', 'Premiere'),
    ('Ragout 6 x 1240 g',
     'Zawiera wszystko, czego potrzebuje Państwa pies. Soczyste mięsne kawałki w rozmiarze XL to wielka radość z gryzienia dla dużych psów. Pyszne wersje wprowadzają różnorodność w misce z karmą.',
     0, 26.94, 'Karma', 'FIT+FUN'),
    ('Opakowanie mieszane Animonda Adult 12 x 400 g',
     'Animonda Carny Adult to zdrowa, pyszna, zbilansowana karma najwyższej jakości dla dorosłych kotów w wieku 1–6 lat.',
     600, 68.40, 'Karma', 'Carny'),
    ('Finest-Mix 5 kg', 'Zbilansowana karma sucha dla Państwa tygryska.', 500, 23.40, 'Karma', 'FIT+FUN'),
    ('Real Nature Wilderness 300g', 'Sucha karma REAL NATURE WILDERNESS Wide Savannah Kitten', 190, 8.99, 'Karma',
     'AniOne'),

    ('Chew It Pałeczki do gryzienia Kaczka 200 g',
     'PREMIERE Pałeczki do gryzienia z piersi kaczki i surowej skóry wołowej są niskotłuszczowymi przekąskami do żucia dla wszystkich psów.',
     1500, 22.90, 'Przekąski', 'Premiere'),
    ('MultiFit native z filetów z kurczaka 1 kg',
     'Zawiera wybrane składniki, tworzy ciekawe wrażenie podczas przeżuwania, nie zawiera sztucznych dodatków.', 200,
     64.99, 'Przekąski', 'Multifit'),
    ('Sensitive Dental Snacks',
     'Przysmaki Select Gold Sensitive Dental Snacks to bardzo dobrze przyswajalne smakołyki jakości premium do pielęgnacji zębów dla psów od 9. miesiąca życia.',
     560, 18.81, 'Przekąski', 'Select Gold'),
    ('Soft Bites 3 x 40 g',
     'Dzięki przekąskom marki PREMIERE właściciele kotów mogą z czystym sumieniem rozpieszczać i nagradzać swoich ulubieńców.',
     550, 23.97, 'Przekąski', 'Premiere'),
    ('Sticks Multipack XXL 250 g', 'Zestaw Multipack zawiera patyczki dla kotów w czterech smacznych wariantach.',
     570, 29.90, 'Przekąski', 'FIT+FUN'),
    ('PREMIO Chicken Octopus Bites 12 x 50 g',
     'Smakowite paski z kurczakiem i ośmiornicą to optymalny przysmak bez glutenu i cukru między posiłkami.',
     580, 58.70, 'Przekąski', 'Trixie'),

    ('Płaska smycz treningowa z pętlą', 'Pozwala kontrolować psa na większej odległości.', 200, 39.99, 'Spacery',
     'AniOne'),
    ('Woreczki na odchody 8 × 20', 'Dla czystszego usuwania odchodów psa.', 2000, 16.90, 'Spacery', 'FIT+FUN'),
    ('Siatka zabezpieczająca',
     'Zapobiega podnoszeniu przez psa niebezpiecznych przedmiotów lub czegokolwiek innego w trakcie spacerów.',
     100, 46.90, 'Spacery', 'Trixie'),
    ('Nylonowe szelki H Classic', 'Szelki Classic wykonano z dobrego jakościowo, wytrzymałego nylonu.',
     140, 42.90, 'Spacery', 'Premiere'),
    ('Obroża skórzana', 'Obroża w jaskrawych letnich kolorach.', 95, 85.90, 'Spacery', 'Multifit'),
    ('Migająca zawieszka LED',
     'Migająca zawieszka LED AniOne zapewni lepszą widoczność Państwa czworonoga o zmierzchu i w ciemności.',
     400, 16.90, 'Spacery', 'AniOne'),

    ('Suchy szampon 100 g',
     'Suchy szampon dla psów, kotów i innych małych zwierząt usuwa zapachy i czyści skórę i sierść Państwa czworonoga bez konieczności kąpieli.',
     700, 22.20, 'Higienia i pielęgnacja', 'Trixie'),
    ('Pęseta do usuwania kleszczy', 'Pęseta marki AniOne umożliwia usunięcie kleszcza bez większego wysiłku.',
     1000, 8.99, 'Higienia i pielęgnacja', 'AniOne'),
    ('Szczotka do czesania', 'Świetnie usuwa zbędną śierść Twojego pupila i przy tym nie podrażnia skóry', 200, 30.90,
     'Higienia i pielęgnacja', 'Carny'),
    ('Excellent Żwirek zbrylający',
     'Żwirek dla kotów PREMIERE Excellent o subtelnym zapachu pudru dla niemowląt jest niezawodny i wyjątkowo szybko pochłania zapachy.',
     150, 49.99, 'Higienia i pielęgnacja', 'Premiere'),
    ('Żwirek fresh comfort',
     'MultiFit fresh comfort summer breeze to niskopylący, zbrylający żwirek o świeżym letnim zapachu dla wszystkich dużych i małych kotów.',
     200, 22.90, 'Higienia i pielęgnacja', 'Multifit'),
    ('Kuweta dla kota Classic Tray',
     'Praktyczna kuweta dla kotów w delikatnym kolorze, idealnie pasuje do każdego wnętrza.',
     60, 19.20, 'Higienia i pielęgnacja', 'FIT+FUN'),

    ('Poduszka do leżenia Bento Oval', 'Owalna poduszka Bento pokryta jest miękkim pluszem.', 120, 42.90,
     'Miejsca do spania', 'FIT+FUN'),
    ('Poduszka do transportera', 'Miękka, przytulna poduszka zapewnia zwierzęciu komfort w transporterze.', 100, 34.90,
     'Miejsca do spania', 'AniOne'),
    ('Legowisko Barry', 'Legowisko z motywem marynistycznym zadowoli zarówno małe psy, jak i koty.', 90, 85.90,
     'Miejsca do spania', 'Trixie'),
    ('Budka Diamond MORE', 'Piękna budka Diamond marki MORE zapewnia świetne miejsce odpoczynku dla Państwa pupila.',
     40, 168.90, 'Miejsca do spania', 'Premiere'),
    ('Legowisko okienne Outlook', 'Rozkładane elementy legowiska chronią przed przeciągiem.', 92, 37.90,
     'Miejsca do spania', 'AniOne'),
    ('Hamak na grzejnik Cloud',
     'Przytulny hamak zapewni Państwa pupilowi ciepłe i miękkie miejsce na wypoczynek w zimne dni i nadaje się do wszystkich popularnych grzejników.',
     20, 188.90, 'Miejsca do spania', 'Select Gold'),

    ('KONG Classic', 'Popularna zabawka dla psów KONG Classic idealnie sprawdza się w rekreacyjnym aportowaniu.', 300,
     34.70, 'Zabawki', 'Trixie'),
    ('Zabawka Piłka na przysmaki',
     'Piłka na przysmaki AniOne to świetna zabawka zapewniająca psu zajęcie, która gwarantuje długotrwałą przyjemność z zabawy.',
     350, 22.40, 'Zabawki', 'AniOne'),
    ('Miotacz + piłka', 'Miotacz to jeszcze większa przyjemność z zabawy w rzucanie i aportowanie!',
     30, 17.90, 'Zabawki', 'FIT+FUN'),
    ('Sznur do zabawy z węzłami',
     'Zabawka bawełniana AniOne to naturalna zabawka dla psów, która daje dużo radości z zabawy.',
     120, 9.90, 'Zabawki', 'Multifit'),
    ('Futrzana mysz zabawka', 'Futrzana mysz pobudza kota do łowów i zabawy.', 400, 3.90, 'Zabawki', 'AniOne'),
    ('Pepe & Kitty Wędka do zabawy',
     'Ta estetyczna wędka do zabawy zapewni każdemu domowemu tygryskowi mnóstwo rozrywki!',
     200, 14.90, 'Zabawki', 'Carny'),
    ('Zabawka Miękkie piłeczki, czteropak',
     'Miękkie piłeczki o żywych kolorach FIT+FUN w praktycznym czteropaku zapewniają świetną zabawę.',
     40, 8.90, 'Zabawki', 'FIT+FUN'),

    ('Plastikowa miska z gumowym pierścieniem', 'Plastikowa miska z praktycznym uchwytem ułatwiającym podnoszenie.',
     120, 9.60, 'Miski i poidełka', 'Trixie'),
    ('Miska na karmę ze stali nierdzewnej, płaska', 'Miska na pokarm ze stali szlachetnej.', 90, 9.60,
     'Miski i poidełka', 'AniOne'),
    ('Dozownik karmy i wody', 'Dwa różne otwory umożliwiają wykorzystanie tego dozownika na karmę lub na wodę.',
     70, 11.30, 'Miski i poidełka', 'Multifit'),
    ('Miska ceramiczna 200 ml', 'Miska ceramiczna dla kotów z zabawnym motywem kota.', 150, 17.50,
     'Miski i poidełka', 'Carny'),
    ('Miska z tworzywa sztucznego Blacky', 'Miska z tworzywa sztucznego AniOne Blacky przekonuje nowoczesnym wzornictwem i komfortowym zastosowaniem.',
     194, 15.90, 'Miski i poidełka', 'AniOne'),
    ('Karmnik Lunchtime', 'Karmnik Lunchtime to praktyczne miejsce na posiłek z 2 miskami.',
     210, 20.20, 'Miski i poidełka', 'FIT+FUN')
)
