"""shop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path
from shop_app import views

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main'),

    path('categories/', views.CategoriesListView.as_view(), name='cat_list'),
    path('category/<int:pk>/', views.CategoryDetailsView.as_view()),
    path('category/add/', views.CategoryAddView.as_view(), name='add_category'),
    path('category/edit/<int:pk>/', views.CategoryEditView.as_view()),
    path('category/delete/<int:pk>/', views.CategoryDeleteView.as_view()),

    path('brands/', views.BrandsListView.as_view(), name='brand_list'),
    path('brand/<int:pk>/', views.BrandDetailsView.as_view()),
    path('brand/add/', views.BrandAddView.as_view(), name='add_brand'),
    path('brand/edit/<int:pk>/', views.BrandEditView.as_view()),

]
# 0005_auto_20201013_1524
# # Generated by Django 3.1.2 on 2020-10-13 15:24
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('shop_app', '0004_auto_20201013_1412'),
#     ]
#
#     operations = [
#         migrations.AlterField(
#             model_name='brand',
#             name='name',
#             field=models.CharField(max_length=100),
#         ),
#     ]

